# Generated by Django 5.2.16 on 2026-08-09 04:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("attendance", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskSuggestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("study", "Self Study"),
                            ("revision", "Revision"),
                            ("assignment", "Assignment"),
                            ("project", "Project Work"),
                            ("reading", "Reading"),
                            ("practice", "Practice Problems"),
                            ("research", "Research"),
                        ],
                        max_length=20,
                    ),
                ),
                ("duration_minutes", models.IntegerField(default=30)),
                ("priority", models.IntegerField(default=1)),
                ("resources_link", models.URLField(blank=True)),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="attendance.subject",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TimeSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day",
                    models.CharField(
                        choices=[
                            ("MON", "Monday"),
                            ("TUE", "Tuesday"),
                            ("WED", "Wednesday"),
                            ("THU", "Thursday"),
                            ("FRI", "Friday"),
                            ("SAT", "Saturday"),
                        ],
                        max_length=3,
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "slot_type",
                    models.CharField(
                        choices=[
                            ("class", "Class"),
                            ("free", "Free Period"),
                            ("lunch", "Lunch Break"),
                            ("lab", "Lab"),
                        ],
                        default="class",
                        max_length=20,
                    ),
                ),
                ("room_number", models.CharField(blank=True, max_length=50)),
                ("department", models.CharField(blank=True, max_length=100)),
                ("year", models.IntegerField(blank=True, null=True)),
                ("section", models.CharField(blank=True, max_length=10)),
                (
                    "class_obj",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_slots",
                        to="attendance.class",
                    ),
                ),
            ],
            options={
                "ordering": ["day", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="DailyPlanner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("custom_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_planners",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "completed_tasks",
                    models.ManyToManyField(
                        blank=True,
                        related_name="completed_by",
                        to="timetable.tasksuggestion",
                    ),
                ),
                (
                    "tasks",
                    models.ManyToManyField(blank=True, to="timetable.tasksuggestion"),
                ),
            ],
            options={
                "unique_together": {("student", "date")},
            },
        ),
    ]
